## Preprocessing

In [2]:
import pandas as pd

In [3]:
df1=pd.read_csv('train.csv')
df2=pd.read_csv('test.csv')

In [4]:
df=pd.concat([df1,df2],axis=0)

In [5]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [6]:
df=df.drop(['PassengerId'],axis=1)

In [7]:
print(df)

     Pclass                                               Name     Sex   Age  \
0         3                            Braund, Mr. Owen Harris    male  22.0
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2         3                             Heikkinen, Miss. Laina  female  26.0
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4         3                           Allen, Mr. William Henry    male  35.0
5         3                                   Moran, Mr. James    male   NaN
6         1                            McCarthy, Mr. Timothy J    male  54.0
7         3                     Palsson, Master. Gosta Leonard    male   2.0
8         3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9         2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0
10        3                    Sandstrom, Miss. Marguerite Rut  female   4.0
11        1                           Bonnell, Miss. Elizabeth  female  58.0
12        3                     Saundercock, Mr. William Henry    male  20.0
13        3                        Andersson, Mr. Anders Johan    male  39.0
14        3               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0
15        2                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0
16        3                               Rice, Master. Eugene    male   2.0
17        2                       Williams, Mr. Charles Eugene    male   NaN
18        3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0
19        3                            Masselmani, Mrs. Fatima  female   NaN
20        2                               Fynney, Mr. Joseph J    male  35.0
21        2                              Beesley, Mr. Lawrence    male  34.0
22        3                        McGowan, Miss. Anna "Annie"  female  15.0
23        1                       Sloper, Mr. William Thompson    male  28.0
24        3                      Palsson, Miss. Torborg Danira  female   8.0
25        3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0
26        3                            Emir, Mr. Farred Chehab    male   NaN
27        1                     Fortune, Mr. Charles Alexander    male  19.0
28        3                      O'Dwyer, Miss. Ellen "Nellie"  female   NaN
29        3                                Todoroff, Mr. Lalio    male   NaN
..      ...                                                ...     ...   ...
388       3                               Canavan, Mr. Patrick    male  21.0
389       3                        Palsson, Master. Paul Folke    male   6.0
390       1                         Payne, Mr. Vivian Ponsonby    male  23.0
391       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)  female  51.0
392       3                      Abbott, Master. Eugene Joseph    male  13.0
393       2                               Gilbert, Mr. William    male  47.0
394       3                           Kink-Heilmann, Mr. Anton    male  29.0
395       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)  female  18.0
396       3                               Colbert, Mr. Patrick    male  24.0
397       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...  female  48.0
398       3                     Larsson-Rondberg, Mr. Edvard A    male  22.0
399       3                           Conlon, Mr. Thomas Henry    male  31.0
400       1                            Bonnell, Miss. Caroline  female  30.0
401       2                                    Gale, Mr. Harry    male  38.0
402       1                     Gibson, Miss. Dorothy Winifred  female  22.0
403       1                             Carrau, Mr. Jose Pedro    male  17.0
404       1                       Frauenthal, Mr. Isaac Gerald    male  43.0
405       2       Nourney, Mr. Alfred (Baron von Drachstedt")"    male  20.0
406       2                          Ware, Mr. William Jeffery    male  23.0
407       1                         Widener, Mr. George Dunton    male  50.0
408       3                    Riordan, Miss. Johanna Hannah""  female   NaN
409       3                          Peacock, Miss. Treasteall  female   3.0
410       3                             Naughton, Miss. Hannah  female   NaN
411       1    Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0
412       3                     Henriksson, Miss. Jenny Lovisa  female  28.0
413       3                                 Spector, Mr. Woolf    male   NaN
414       1                       Oliva y Ocana, Dona. Fermina  female  39.0
415       3                       Saether, Mr. Simon Sivertsen    male  38.5
416       3                                Ware, Mr. Frederick    male   NaN
417       3                           Peter, Master. Michael J    male   NaN

     SibSp  Parch              Ticket      Fare        Cabin Embarked  \
0        1      0           A/5 21171    7.2500          NaN        S
1        1      0            PC 17599   71.2833          C85        C
2        0      0    STON/O2. 3101282    7.9250          NaN        S
3        1      0              113803   53.1000         C123        S
4        0      0              373450    8.0500          NaN        S
5        0      0              330877    8.4583          NaN        Q
6        0      0               17463   51.8625          E46        S
7        3      1              349909   21.0750          NaN        S
8        0      2              347742   11.1333          NaN        S
9        1      0              237736   30.0708          NaN        C
10       1      1             PP 9549   16.7000           G6        S
11       0      0              113783   26.5500         C103        S
12       0      0           A/5. 2151    8.0500          NaN        S
13       1      5              347082   31.2750          NaN        S
14       0      0              350406    7.8542          NaN        S
15       0      0              248706   16.0000          NaN        S
16       4      1              382652   29.1250          NaN        Q
17       0      0              244373   13.0000          NaN        S
18       1      0              345763   18.0000          NaN        S
19       0      0                2649    7.2250          NaN        C
20       0      0              239865   26.0000          NaN        S
21       0      0              248698   13.0000          D56        S
22       0      0              330923    8.0292          NaN        Q
23       0      0              113788   35.5000           A6        S
24       3      1              349909   21.0750          NaN        S
25       1      5              347077   31.3875          NaN        S
26       0      0                2631    7.2250          NaN        C
27       3      2               19950  263.0000  C23 C25 C27        S
28       0      0              330959    7.8792          NaN        Q
29       0      0              349216    7.8958          NaN        S
..     ...    ...                 ...       ...          ...      ...
388      0      0              364858    7.7500          NaN        Q
389      3      1              349909   21.0750          NaN        S
390      0      0               12749   93.5000          B24        S
391      0      1            PC 17592   39.4000          D28        S
392      0      2           C.A. 2673   20.2500          NaN        S
393      0      0          C.A. 30769   10.5000          NaN        S
394      3      1              315153   22.0250          NaN        S
395      1      0               13695   60.0000          C31        S
396      0      0              371109    7.2500          NaN        Q
397      1      1               13567   79.2000          B41        C
398      0      0              347065    7.7750          NaN        S
399      0      0               21332    7.7333          NaN        Q
400      0      0               36928  164.8667           C7        S
401      1      0               28664   21.0000          NaN        S
402      0      1              112378   59.4000          NaN        C
403      0      0              113059   47.1000          NaN        S
404      1      0               17765   27.7208          D40        C
405      0      0       SC/PARIS 2166   13.8625          D38        C
406      1      0               28666   10.5000          NaN        S
407      1      1              113503  211.5000          C80        C
408      0      0              334915    7.7208          NaN        Q
409      1      1  SOTON/O.Q. 3101315   13.7750          NaN        S
410      0      0              365237    7.7500          NaN        Q
411      1      0               19928   90.0000          C78        Q
412      0      0              347086    7.7750          NaN        S
413      0      0           A.5. 3236    8.0500          NaN        S
414      0      0            PC 17758  108.9000         C105        C
415      0      0  SOTON/O.Q. 3101262    7.2500          NaN        S
416      0      0              359309    8.0500          NaN        S
417      1      1                2668   22.3583          NaN        C

     Survived
0           0
1           1
2           1
3           1
4           0
5           0
6           0
7           0
8           1
9           1
10          1
11          1
12          0
13          0
14          0
15          1
16          0
17          1
18          0
19          1
20          0
21          1
22          1
23          1
24          0
25          1
26          0
27          0
28          1
29          0
..        ...
388         0
389         0
390         0
391         1
392         0
393         0
394         0
395         1
396         0
397         1
398         0
399         0
400         1
401         0
402         1
403         0
404         0
405         0
406         0
407         0
408         1
409         1
410         1
411         1
412         1
413         0
414         1
415         0
416         0
417         0

[1309 rows x 11 columns]

In [8]:
i=0
name=[]
while i<len(df):
    #print(df.iloc[i]['Name'].type)
    
    if "Mrs." in df.iloc[i]['Name']:
        name.append(str(1))
        print("a")
    elif 'Mr.' in df.iloc[i]['Name']:
        name.append(str(2))
        print("b")
    elif "Miss." in df.iloc[i]['Name']:
        name.append(str(3))
        print("c")
    elif "Master." in df.iloc[i]["Name"]:
        name.append(str(4))
        print("d")
    else:
        name.append(str(5))
    i+=1

df['name']=name

b
a
c
a
b
b
b
d
a
a
c
c
b
b
c
a
d
b
a
a
b
b
c
b
c
a
b
b
c
b
a
c
b
b
b
b
b
c
c
a
a
b
c
c
b
b
c
b
a
d
b
a
a
b
b
c
b
c
d
b
c
b
d
b
d
a
b
c
b
b
c
b
b
b
b
b
b
d
c
b
b
c
b
c
a
b
b
c
b
b
b
b
b
b
b
b
b
a
b
c
b
b
b
b
b
c
b
b
c
b
c
b
c
c
b
b
b
b
c
b
b
b
c
b
d
b
b
c
b
b
b
a
a
b
b
c
b
b
b
a
c
a
b
b
b
b
c
b
a
b
b
b
b
c
b
b
d
b
a
b
b
d
d
a
a
b
b
b
d
c
b
b
b
d
c
b
b
c
b
d
d
c
b
a
b
b
b
a
b
c
d
a
c
b
b
c
c
b
b
b
b
b
c
b
b
c
b
b
c
b
b
b
c
c
b
c
b
b
b
b
b
b
b
b
b
b
c
a
b
b
c
b
c
b
c
b
b
c
c
b
b
b
c
a
b
b
a
b
b
a
a
a
c
c
a
b
d
b
b
c
b
b
b
a
c
b
b
a
b
c
c
c
b
d
a
b
b
b
b
b
b
b
b
b
c
c
a
b
c
b
b
b
c
b
a
c
b
b
c
b
d
c
a
b
c
c
c
a
b
b
c
a
c
a
b
b
c
a
b
c
b
a
a
c
c
b
b
b
a
b
b
c
b
b
d
c
b
b
b
c
c
a
d
b
b
b
b
b
b
b
c
c
c
c
b
b
a
b
b
b
a
a
c
b
b
b
b
c
a
c
b
b
b
c
c
b
a
b
b
d
c
b
c
b
b
b
c
a
b
c
b
a
b
b
c
b
c
b
b
d
b
c
b
b
c
b
b
a
a
c
b
c
b
b
b
a
b
b
a
c
b
b
b
a
a
b
b
c
c
a
b
b
a
b
b
b
d
c
b
c
b
b
b
b
b
b
b
a
c
b
b
b
b
b
b
b
b
b
b
c
b
b
a
a
c
b
b
b
b
c
d
b
b
a
b
c
a
b
b
d
b
b
b
b
b
b
c
b
a
b
b
c
c
c
c
b
a
b
b
b
b
b
b
a
b
b
a
b
a
b
c
b
b
a
b
b
c
b
b
b
c
b
b
a
c
c
c
b
c
c
c
c
b
b
b
a
b
b
d
b
b
b
b
c
b
b
a
a
b
b
b
b
c
b
b
a
b
b
b
a
b
c
b
b
c
a
a
b
c
a
b
b
b
c
b
b
b
b
b
a
b
c
b
b
c
b
b
a
b
b
b
b
b
b
b
a
c
a
b
c
b
b
c
b
a
c
b
b
b
b
b
b
b
c
b
b
b
b
b
c
c
b
b
a
b
b
c
b
c
b
b
b
c
b
c
b
c
c
b
b
a
b
b
b
b
b
b
b
b
b
b
a
a
b
b
b
b
b
b
c
a
b
c
b
b
b
b
b
b
b
b
c
b
c
b
b
b
b
c
b
b
a
b
c
b
b
b
a
b
c
d
b
b
b
b
b
c
c
b
b
c
b
b
b
b
b
a
c
b
c
c
b
b
b
b
b
a
b
b
b
b
b
c
b
b
b
c
b
b
c
d
b
b
a
d
b
b
b
b
b
b
a
b
a
c
b
b
b
b
a
b
a
b
b
c
b
a
c
a
b
b
b
b
c
d
d
b
b
b
c
b
b
b
a
b
a
b
a
d
d
b
b
b
c
b
a
b
b
b
c
b
b
c
b
b
d
a
b
a
d
b
b
d
b
a
a
d
b
b
b
c
b
b
b
b
b
b
c
b
b
b
b
b
a
d
b
c
c
a
a
a
b
a
b
b
b
a
c
b
a
c
b
b
d
b
a
b
b
a
c
b
b
b
a
a
b
c
b
b
a
c
c
b
b
b
a
b
b
a
b
c
b
a
b
b
b
a
b
a
a
b
b
c
a
b
d
a
b
a
b
c
b
b
b
b
b
a
a
b
b
c
c
b
b
b
b
b
a
a
b
b
b
a
a
b
b
c
c
b
d
b
b
b
c
b
b
b
c
d
a
c
b
b
a
c
b
c
b
c
b
b
a
b
c
d
b
b
b
b
b
c
c
d
a
b
a
b
b
b
a
b
c
b
a
b
b
b
a
b
b
b
b
b
b
c
c
c
a
b
b
c
b
a
c
b
a
b
b
c
b
c
b
b
b
a
b
b
b
b
b
c
b
c
c
b
b
b
b
b
b
b
a
b
b
a
d
b
c
c
b
a
c
d
c
b
a
b
b
a
c
b
b
b
b
b
c
c
b
a
a
b
b
a
b
a
b
c
b
c
b
b
b
d
b
d
b
d
c
b
a
c
d
c
b
b
c
b
c
b
b
b
b
a
c
b
c
b
a
b
c
b
a
b
a
a
b
c
b
b
b
c
b
b
b
b
b
b
c
a
a
a
b
b
d
b
a
b
a
a
c
b
b
b
b
b
b
b
c
b
b
b
a
c
b
b
b
b
c
b
b
b
a
c
b
c
b
b
b
b
c
d
c
c
c
b
b
b
b
b
b
c
b
b
b
c
b
b
b
b
b
b
b
c
a
b
d
b
a
b
b
b
c
a
c
b
b
b
b
b
b
b
b
c
b
c
b
b
b
a
b
b
a
b
b
b
b
b
d
b
b
b
a
d
c
b
a
b
c
a
b
b
b
c
b
a
b
b
a
d
a
a
b
a
a
b
c
a
b
b
c
b
b
a
c
c
b
b
d
b
b
a
a
b
c
b
b
b
d
b
a
d
b
b
a
b
a
b
b
c
b
c
b
b
b
b
b
c
c
c
a
c
b
b
b
d

In [9]:
df=df.drop(['Name'],axis=1)
df.head()

,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived,name
0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2
1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1,1
2,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,3
3,1,female,35.0,1,0,113803,53.1000,C123,S,1,1
4,3,male,35.0,0,0,373450,8.0500,NaN,S,0,2

In [10]:
i=0
siblings=[]
df.fillna(0)
while i<len(df):
    if df.iloc[i]['SibSp']>0:
        siblings.append(str(1))
    else:
        siblings.append(str(0))
        
    i+=1
df=df.drop(["SibSp"],axis=1)
df["Siblings"]=siblings

In [11]:
df.head()

,Pclass,Sex,Age,Parch,Ticket,Fare,Cabin,Embarked,Survived,name,Siblings
0,3,male,22.0,0,A/5 21171,7.2500,NaN,S,0,2,1
1,1,female,38.0,0,PC 17599,71.2833,C85,C,1,1,1
2,3,female,26.0,0,STON/O2. 3101282,7.9250,NaN,S,1,3,0
3,1,female,35.0,0,113803,53.1000,C123,S,1,1,1
4,3,male,35.0,0,373450,8.0500,NaN,S,0,2,0

In [12]:
i=0
parent=[]
df.fillna(0)
while i<len(df):
    if df.iloc[i]['Parch']>0:
        parent.append(str(1))
    else:
        parent.append(str(0))
        
    i+=1
df=df.drop(["Parch"],axis=1)
df["Parent"]=parent

In [13]:
df.head()

,Pclass,Sex,Age,Ticket,Fare,Cabin,Embarked,Survived,name,Siblings,Parent
0,3,male,22.0,A/5 21171,7.2500,NaN,S,0,2,1,0
1,1,female,38.0,PC 17599,71.2833,C85,C,1,1,1,0
2,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S,1,3,0,0
3,1,female,35.0,113803,53.1000,C123,S,1,1,1,0
4,3,male,35.0,373450,8.0500,NaN,S,0,2,0,0

In [14]:
df['Age'].fillna(df['Age'].mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
5      29.881138
6      54.000000
7       2.000000
8      27.000000
9      14.000000
10      4.000000
11     58.000000
12     20.000000
13     39.000000
14     14.000000
15     55.000000
16      2.000000
17     29.881138
18     31.000000
19     29.881138
20     35.000000
21     34.000000
22     15.000000
23     28.000000
24      8.000000
25     38.000000
26     29.881138
27     19.000000
28     29.881138
29     29.881138
         ...
388    21.000000
389     6.000000
390    23.000000
391    51.000000
392    13.000000
393    47.000000
394    29.000000
395    18.000000
396    24.000000
397    48.000000
398    22.000000
399    31.000000
400    30.000000
401    38.000000
402    22.000000
403    17.000000
404    43.000000
405    20.000000
406    23.000000
407    50.000000
408    29.881138
409     3.000000
410    29.881138
411    37.000000
412    28.000000
413    29.881138
414    39.000000
415    38.500000
416    29.881138
417    29.881138
Name: Age, Length: 1309, dtype: float64

In [15]:
i=0
age=[]
while i<len(df):
    if df.iloc[i]['Age']<15:
        age.append(str(1))
    elif df.iloc[i]['Age']<30:
        age.append(str(2))
    elif df.iloc[i]['Age']<45:
        age.append(str(3))
    elif df.iloc[i]['Age']<60:
        age.append(str(4))
    else:
        age.append(str(5))
    i+=1

In [16]:
df['age']=age

In [17]:
df=df.drop(['Age'],axis=1)

In [18]:
df['Fare'].fillna(df['Fare'].mean())

0        7.2500
1       71.2833
2        7.9250
3       53.1000
4        8.0500
5        8.4583
6       51.8625
7       21.0750
8       11.1333
9       30.0708
10      16.7000
11      26.5500
12       8.0500
13      31.2750
14       7.8542
15      16.0000
16      29.1250
17      13.0000
18      18.0000
19       7.2250
20      26.0000
21      13.0000
22       8.0292
23      35.5000
24      21.0750
25      31.3875
26       7.2250
27     263.0000
28       7.8792
29       7.8958
         ...
388      7.7500
389     21.0750
390     93.5000
391     39.4000
392     20.2500
393     10.5000
394     22.0250
395     60.0000
396      7.2500
397     79.2000
398      7.7750
399      7.7333
400    164.8667
401     21.0000
402     59.4000
403     47.1000
404     27.7208
405     13.8625
406     10.5000
407    211.5000
408      7.7208
409     13.7750
410      7.7500
411     90.0000
412      7.7750
413      8.0500
414    108.9000
415      7.2500
416      8.0500
417     22.3583
Name: Fare, Length: 1309, dtype: float64

In [19]:
i=0
fare=[]
while i<len(df):
    if df.iloc[i]['Fare']<15:
        fare.append(str(1))
    elif df.iloc[i]['Fare']<55:
        fare.append(str(2))
    elif df.iloc[i]['Fare']<120:
        fare.append(str(3))
    elif df.iloc[i]['Fare']<190:
        fare.append(str(4))
    else:
        fare.append(str(5))
    i+=1

In [20]:
df['fare']=fare

In [21]:
df=df.drop(['Fare'],axis=1)

In [22]:
i=0
ticket=[]
while i<len(df):
    if df.iloc[i]['Ticket'].isnumeric():
        ticket.append(str(1))
    else:
        ticket.append(str(0))
    i+=1

In [23]:
df['ticket']=ticket

In [24]:
df=df.drop(['Ticket'],axis=1)

In [25]:
z=0
df['Cabin'].fillna("NA")
cabin=[]
while z<len(df):
    print(df.iloc[z]['Cabin'])
    if 'a' in str(df.iloc[z]['Cabin']):
        cabin.append(str(0))
    else:
        cabin.append(str(1))
    z+=1

nan
C85
nan
C123
nan
nan
E46
nan
nan
nan
G6
C103
nan
nan
nan
nan
nan
nan
nan
nan
nan
D56
nan
A6
nan
nan
nan
C23 C25 C27
nan
nan
nan
B78
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
D33
nan
B30
C52
nan
nan
nan
nan
nan
B28
C83
nan
nan
nan
F33
nan
nan
nan
nan
nan
nan
nan
nan
F G73
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C23 C25 C27
nan
nan
nan
E31
nan
nan
nan
A5
D10 D12
nan
nan
nan
nan
D26
nan
nan
nan
nan
nan
nan
nan
C110
nan
nan
nan
nan
nan
nan
nan
B58 B60
nan
nan
nan
nan
E101
D26
nan
nan
nan
F E69
nan
nan
nan
nan
nan
nan
nan
D47
C123
nan
B86
nan
nan
nan
nan
nan
nan
nan
nan
F2
nan
nan
C2
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
E33
nan
nan
nan
B19
nan
nan
nan
A7
nan
nan
C49
nan
nan
nan
nan
nan
F4
nan
A32
nan
nan
nan
nan
nan
nan
nan
F2
B4
B80
nan
nan
nan
nan
nan
nan
nan
nan
nan
G6
nan
nan
nan
A31
nan
nan
nan
nan
nan
D36
nan
nan
D15
nan
nan
nan
nan
nan
C93
nan
nan
nan
nan
nan
C83
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C78
nan
nan
D35
nan
nan
G6
C87
nan
nan
nan
nan
B77
nan
nan
nan
nan
E67
B94
nan
nan
nan
nan
C125
C99
nan
nan
nan
C118
nan
D7
nan
nan
nan
nan
nan
nan
nan
nan
A19
nan
nan
nan
nan
nan
nan
B49
D
nan
nan
nan
nan
C22 C26
C106
B58 B60
nan
nan
nan
E101
nan
C22 C26
nan
C65
nan
E36
C54
B57 B59 B63 B66
nan
nan
nan
nan
nan
nan
C7
E34
nan
nan
nan
nan
nan
C32
nan
D
nan
B18
nan
C124
C91
nan
nan
nan
C2
E40
nan
T
F2
C23 C25 C27
nan
nan
nan
F33
nan
nan
nan
nan
nan
C128
nan
nan
nan
nan
E33
nan
nan
nan
nan
nan
nan
nan
nan
nan
D37
nan
nan
B35
E50
nan
nan
nan
nan
nan
nan
C82
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
B96 B98
nan
nan
D36
G6
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C78
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
E10
C52
nan
nan
nan
E44
B96 B98
nan
nan
C23 C25 C27
nan
nan
nan
nan
nan
nan
A34
nan
nan
nan
C104
nan
nan
C111
C92
nan
nan
E38
D21
nan
nan
E12
nan
E63
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
D
nan
A14
nan
nan
nan
nan
nan
nan
nan
nan
B49
nan
C93
B37
nan
nan
nan
nan
C30
nan
nan
nan
D20
nan
C22 C26
nan
nan
nan
nan
nan
B79
C65
nan
nan
nan
nan
nan
nan
E25
nan
nan
D46
F33
nan
nan
nan
B73
nan
nan
B18
nan
nan
nan
C95
nan
nan
nan
nan
nan
nan
nan
nan
B38
nan
nan
B39
B22
nan
nan
nan
C86
nan
nan
nan
nan
nan
C70
nan
nan
nan
nan
nan
A16
nan
E67
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C101
E25
nan
nan
nan
nan
E44
nan
nan
nan
C68
nan
A10
nan
E68
nan
B41
nan
nan
nan
D20
nan
nan
nan
nan
nan
nan
nan
A20
nan
nan
nan
nan
nan
nan
nan
nan
nan
C125
nan
nan
nan
nan
nan
nan
nan
nan
F4
nan
nan
D19
nan
nan
nan
D50
nan
D9
nan
nan
A23
nan
B50
nan
nan
nan
nan
nan
nan
nan
nan
B35
nan
nan
nan
D33
nan
A26
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
D48
nan
nan
E58
nan
nan
nan
nan
nan
nan
C126
nan
B71
nan
nan
nan
nan
nan
nan
nan
B51 B53 B55
nan
D49
nan
nan
nan
nan
nan
nan
nan
B5
B20
nan
nan
nan
nan
nan
nan
nan
C68
F G63
C62 C64
E24
nan
nan
nan
nan
nan
E24
nan
nan
C90
C124
C126
nan
nan
F G73
C45
E101
nan
nan
nan
nan
nan
nan
E8
nan
nan
nan
nan
nan
B5
nan
nan
nan
nan
nan
nan
B101
nan
nan
D45
C46
B57 B59 B63 B66
nan
nan
B22
nan
nan
D30
nan
nan
E121
nan
nan
nan
nan
nan
nan
nan
B77
nan
nan
nan
B96 B98
nan
D11
nan
nan
nan
nan
nan
nan
E77
nan
nan
nan
F38
nan
nan
B3
nan
B20
D6
nan
nan
nan
nan
nan
nan
B82 B84
nan
nan
nan
nan
nan
nan
D17
nan
nan
nan
nan
nan
B96 B98
nan
nan
nan
A36
nan
nan
E8
nan
nan
nan
nan
nan
B102
nan
nan
nan
nan
B69
nan
nan
E121
nan
nan
nan
nan
nan
B28
nan
nan
nan
nan
nan
E49
nan
nan
nan
C47
nan
nan
nan
nan
nan
nan
nan
nan
nan
C92
nan
nan
nan
D28
nan
nan
nan
E17
nan
nan
nan
nan
D17
nan
nan
nan
nan
A24
nan
nan
nan
D35
B51 B53 B55
nan
nan
nan
nan
nan
nan
C50
nan
nan
nan
nan
nan
nan
nan
B42
nan
C148
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
B45
nan
E31
nan
nan
nan
nan
nan
nan
nan
nan
nan
B57 B59 B63 B66
nan
B36
nan
A21
nan
nan
nan
nan
nan
C78
nan
nan
nan
nan
nan
nan
D34
nan
nan
D19
nan
A9
nan
D15
nan
C31
nan
nan
C23 C25 C27
nan
nan
nan
F G63
nan
B61
nan
nan
nan
nan
B57 B59 B63 B66
nan
nan
nan
C53
C23 C25 C27
nan
nan
nan
D43
C130
C132
nan
C101
nan
nan
nan
C55 C57
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
B71
nan
nan
nan
C46
nan
nan
nan
C116
nan
nan
nan
nan
nan
nan
nan
nan
F
nan
nan
A29
nan
C55 C57
nan
nan
G6
C6
nan
nan
nan
C28
nan
nan
nan
nan
nan
nan
nan
nan
C51
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
B57 B59 B63 B66
nan
nan
nan
E46
nan
nan
nan
C54
nan
nan
nan
nan
nan
C97
nan
D22
nan
nan
nan
nan
nan
nan
nan
B10
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C116
F4
E45
nan
E52
D30
nan
B58 B60
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
E34
nan
nan
nan
nan
nan
C62 C64
nan
nan
nan
nan
nan
A11
nan
nan
nan
nan
nan
nan
B11
nan
nan
C80
nan
nan
nan
F33
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C85
nan
D37
nan
nan
C86
nan
nan
E34
nan
nan
D21
nan
nan
nan
nan
nan
nan
C89
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C6
nan
C89
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
B45
F E46
nan
nan
nan
nan
A34
nan
nan
nan
nan
nan
nan
nan
D
nan
nan
nan
B26
C22 C26
nan
B69
nan
nan
nan
nan
nan
C32
nan
B78
nan
nan
nan
nan
F E57
F2
nan
nan
nan
F4
nan
nan
nan
nan
A18
nan
nan
nan
C106
nan
nan
nan
nan
nan
nan
nan
B51 B53 B55
nan
nan
nan
nan
nan
nan
D10 D12
nan
nan
nan
nan
E60
C101
nan
nan
nan
nan
nan
nan
nan
E50
nan
nan
nan
nan
nan
nan
E39 E41
B52 B54 B56
nan
A34
nan
nan
nan
C39
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
B24
D28
nan
nan
nan
C31
nan
B41
nan
nan
C7
nan
nan
nan
D40
D38
nan
C80
nan
nan
nan
C78
nan
nan
C105
nan
nan
nan

In [26]:
df['cabin']=cabin

In [27]:
df=df.drop(['Cabin'],axis=1)

In [28]:
df.head()

,Pclass,Sex,Embarked,Survived,name,Siblings,Parent,age,fare,ticket,cabin
0,3,male,S,0,2,1,0,2,1,0,0
1,1,female,C,1,1,1,0,3,3,0,1
2,3,female,S,1,3,0,0,2,1,0,0
3,1,female,S,1,1,1,0,3,2,1,1
4,3,male,S,0,2,0,0,3,1,1,0

In [29]:
df.to_csv('cleaned.csv',index=False)

In [30]:
df

,Pclass,Sex,Embarked,Survived,name,Siblings,Parent,age,fare,ticket,cabin
0,3,male,S,0,2,1,0,2,1,0,0
1,1,female,C,1,1,1,0,3,3,0,1
2,3,female,S,1,3,0,0,2,1,0,0
3,1,female,S,1,1,1,0,3,2,1,1
4,3,male,S,0,2,0,0,3,1,1,0
5,3,male,Q,0,2,0,0,5,1,1,0
6,1,male,S,0,2,0,0,4,2,1,1
7,3,male,S,0,4,1,1,1,2,1,0
8,3,female,S,1,1,0,1,2,1,1,0
9,2,female,C,1,1,1,0,1,2,1,0
10,3,female,S,1,3,1,1,1,2,0,1
11,1,female,S,1,3,0,0,4,2,1,1
12,3,male,S,0,2,0,0,2,1,0,0
13,3,male,S,0,2,1,1,3,2,1,0
14,3,female,S,0,3,0,0,1,1,1,0
15,2,female,S,1,1,0,0,4,2,1,0
16,3,male,Q,0,4,1,1,1,2,1,0
17,2,male,S,1,2,0,0,5,1,1,0
18,3,female,S,0,1,1,0,3,2,1,0
19,3,female,C,1,1,0,0,5,1,1,0
20,2,male,S,0,2,0,0,3,2,1,0
21,2,male,S,1,2,0,0,3,1,1,1
22,3,female,Q,1,3,0,0,2,1,1,0
23,1,male,S,1,2,0,0,2,2,1,1
24,3,female,S,0,3,1,1,1,2,1,0
25,3,female,S,1,1,1,1,3,2,1,0
26,3,male,C,0,2,0,0,5,1,1,0
27,1,male,S,0,2,1,1,2,5,1,1
28,3,female,Q,1,3,0,0,5,1,1,0
29,3,male,S,0,2,0,0,5,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
388,3,male,Q,0,2,0,0,2,1,1,0
389,3,male,S,0,4,1,1,1,2,1,0
390,1,male,S,0,2,0,0,2,3,1,1
391,1,female,S,1,1,0,1,4,2,0,1
392,3,male,S,0,4,0,1,1,2,0,0
393,2,male,S,0,2,0,0,4,1,0,0
394,3,male,S,0,2,1,1,2,2,1,0
395,1,female,S,1,1,1,0,2,3,1,1
396,3,male,Q,0,2,0,0,2,1,1,0
397,1,female,C,1,1,1,1,4,3,1,1
398,3,male,S,0,2,0,0,2,1,1,0
399,3,male,Q,0,2,0,0,3,1,1,0
400,1,female,S,1,3,0,0,3,4,1,1
401,2,male,S,0,2,1,0,3,2,1,0
402,1,female,C,1,3,0,1,2,3,1,0
403,1,male,S,0,2,0,0,2,2,1,0
404,1,male,C,0,2,1,0,3,2,1,1
405,2,male,C,0,2,0,0,2,1,0,1
406,2,male,S,0,2,1,0,2,1,1,0
407,1,male,C,0,2,1,1,4,5,1,1
408,3,female,Q,1,3,0,0,5,1,1,0
409,3,female,S,1,3,1,1,1,1,0,0
410,3,female,Q,1,3,0,0,5,1,1,0
411,1,female,Q,1,1,1,0,3,3,1,1
412,3,female,S,1,3,0,0,2,1,1,0
413,3,male,S,0,2,0,0,5,1,0,0
414,1,female,C,1,5,0,0,3,3,0,1
415,3,male,S,0,2,0,0,3,1,0,0
416,3,male,S,0,2,0,0,5,1,1,0
417,3,male,C,0,4,1,1,5,2,1,0

### Dataset Creation

In [31]:
df1=pd.get_dummies(df,columns=['Pclass','Sex',"Embarked",'name','Siblings','Parent','age','fare','ticket','cabin'])

In [32]:
df1.head()

,Survived,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,name_1,...,age_5,fare_1,fare_2,fare_3,fare_4,fare_5,ticket_0,ticket_1,cabin_0,cabin_1
0,0,0,0,1,0,1,0,0,1,0,...,0,1,0,0,0,0,1,0,1,0
1,1,1,0,0,1,0,1,0,0,1,...,0,0,0,1,0,0,1,0,0,1
2,1,0,0,1,1,0,0,0,1,0,...,0,1,0,0,0,0,1,0,1,0
3,1,1,0,0,1,0,0,0,1,1,...,0,0,1,0,0,0,0,1,0,1
4,0,0,0,1,0,1,0,0,1,0,...,0,1,0,0,0,0,0,1,1,0

In [42]:
Y=[0]*len(df1)

In [43]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(df1,Y,test_size=0.3, random_state=42)

In [46]:
X_train.to_csv('cleaned_train.csv',index=False)

In [47]:
X_test.to_csv('cleaned_test.csv',index=False)

In [36]:
df1.to_csv('cleaned.csv',index=False)

In [53]:
len(X_train.columns)

32

In [34]:
from torch.utils.data import Dataset, DataLoader

### Pytorch Dataset Generation and Loading

In [111]:
class Gen_Dataset(Dataset):
    
    def __init__(self,file, mode='train'):
        self.mode=mode
        df=pd.read_csv(file)
        
        if self.mode=='train':
            self.oup=df['Survived'].values.reshape(len(df),1)
            df1=df.drop(['Survived'],axis=1)
            self.inp=df1.values
        else:
            df1=df.drop(['Survived'],axis=1)
            self.inp=df1.values
    
    def __len__(self):
        return len(self.inp)
    
    def __getitem__(self,idx):
        if self.mode=='train':
            inpt=torch.tensor(self.inp[idx])
            oupt=torch.tensor(self.oup[idx])
            
            return { 'inp': inpt,
                    'oup':oupt,
                   }
        else:
            inpt=torch.Tensor(self.inp[idx])
            return { 'inp': inpt
                   }

In [112]:
data=Gen_Dataset('cleaned_train.csv')

In [113]:
data

In [182]:
data_train=DataLoader(dataset=data,batch_size=32,shuffle=False)

### Modelling

In [183]:
import torch.nn as nn
import torch.nn.functional as func

In [184]:
class Neural_Net(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.fc1=nn.Linear(31,64)
        self.fc2=nn.Linear(64,128)
        self.fc3=nn.Linear(128,128)
        self.fc4=nn.Linear(128,256)
        self.fc5=nn.Linear(256,1)
        
    def forward(self,x):
        
        x=func.relu(self.fc1(x))
        x=func.relu(self.fc2(x))
        x=func.relu(self.fc3(x))
        x=func.relu(self.fc4(x))
        x=func.sigmoid(self.fc5(x))
        
        return x

In [185]:
from torch.optim import Adam

In [197]:
criterion=nn.MSELoss()

In [208]:
Epochs=200

In [209]:
netw=Neural_Net()

In [210]:
netw

Neural_Net(
  (fc1): Linear(in_features=31, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=128, bias=True)
  (fc4): Linear(in_features=128, out_features=256, bias=True)
  (fc5): Linear(in_features=256, out_features=1, bias=True)
)

In [211]:
optm=Adam(netw.parameters(),lr=0.001)

In [216]:
def train(model,x,y,optimizer,criterion,batch_size):
    model.zero_grad()
    output=model(x.float())
    #print(output)
    #print(y)
    #loss=0
    #for i in range(len(output)):
    loss=criterion(output,y.float())
    #loss=loss/batch_size
    loss.backward()
    optimizer.step()
    
    return loss, output

In [217]:
import torch
from tqdm import tqdm

In [218]:
div=0
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    div=1
    print("Cuda Device Available")

### Training

In [219]:
for epoch in range(Epochs):
    epoch_loss = 0
    correct = 0
    for bidx, batch in tqdm(enumerate(data_train)):
        x_train, y_train = batch['inp'], batch['oup']
        #x_train = x_train.view(-1,31)
        #y_train = y_train.view(-1,1)
        #print(x_train)
        #print(y_train)
        if div==1:
            x_train = x_train.to(device)
            y_train = y_train.to(device)
        loss, predictions = train(netw,x_train,y_train, optm, criterion,batch_size=32)
        for idx, i in enumerate(predictions):
            i  = torch.round(i)
            if i == y_train[idx]:
                correct += 1
        acc = (correct/len(data))
        epoch_loss+=loss
    print('Epoch {} Accuracy : {}'.format(epoch+1, acc*100))
    print('Epoch {} Loss : {}'.format((epoch+1),epoch_loss))

29it [00:00, 162.52it/s]
29it [00:00, 187.46it/s]
0it [00:00, ?it/s]

Epoch 1 Accuracy : 67.79475982532752
Epoch 1 Loss : 5.768831729888916
Epoch 2 Accuracy : 85.26200873362446
Epoch 2 Loss : 3.492279529571533

29it [00:00, 178.44it/s]
29it [00:00, 178.16it/s]
0it [00:00, ?it/s]

Epoch 3 Accuracy : 86.02620087336244
Epoch 3 Loss : 3.3086588382720947
Epoch 4 Accuracy : 86.46288209606988
Epoch 4 Loss : 3.1475982666015625

29it [00:00, 184.39it/s]
29it [00:00, 192.04it/s]
0it [00:00, ?it/s]

Epoch 5 Accuracy : 86.57205240174673
Epoch 5 Loss : 3.059088706970215
Epoch 6 Accuracy : 87.117903930131
Epoch 6 Loss : 2.981644630432129

29it [00:00, 175.02it/s]
29it [00:00, 155.47it/s]
0it [00:00, ?it/s]

Epoch 7 Accuracy : 87.44541484716157
Epoch 7 Loss : 2.9128127098083496
Epoch 8 Accuracy : 87.77292576419214
Epoch 8 Loss : 2.853372097015381

29it [00:00, 137.48it/s]
29it [00:00, 179.91it/s]
0it [00:00, ?it/s]

Epoch 9 Accuracy : 87.882096069869
Epoch 9 Loss : 2.791377544403076
Epoch 10 Accuracy : 88.42794759825327
Epoch 10 Loss : 2.7308952808380127

29it [00:00, 156.49it/s]
12it [00:00, 115.55it/s]

Epoch 11 Accuracy : 88.64628820960698
Epoch 11 Loss : 2.6648380756378174

29it [00:00, 137.89it/s]
29it [00:00, 173.10it/s]
0it [00:00, ?it/s]

Epoch 12 Accuracy : 89.08296943231441
Epoch 12 Loss : 2.59808349609375
Epoch 13 Accuracy : 89.51965065502183
Epoch 13 Loss : 2.523890733718872

29it [00:00, 138.78it/s]
14it [00:00, 135.13it/s]

Epoch 14 Accuracy : 89.8471615720524
Epoch 14 Loss : 2.4693870544433594

29it [00:00, 139.68it/s]
13it [00:00, 125.16it/s]

Epoch 15 Accuracy : 90.28384279475983
Epoch 15 Loss : 2.41530704498291

29it [00:00, 102.20it/s]
10it [00:00, 94.75it/s]

Epoch 16 Accuracy : 90.28384279475983
Epoch 16 Loss : 2.387479066848755

29it [00:00, 104.66it/s]
12it [00:00, 116.60it/s]

Epoch 17 Accuracy : 90.28384279475983
Epoch 17 Loss : 2.37904953956604

29it [00:00, 127.52it/s]
29it [00:00, 177.92it/s]
0it [00:00, ?it/s]

Epoch 18 Accuracy : 89.95633187772926
Epoch 18 Loss : 2.3625056743621826
Epoch 19 Accuracy : 90.61135371179039
Epoch 19 Loss : 2.295910120010376

29it [00:00, 180.16it/s]
29it [00:00, 178.74it/s]
0it [00:00, ?it/s]

Epoch 20 Accuracy : 90.72052401746726
Epoch 20 Loss : 2.2728466987609863
Epoch 21 Accuracy : 90.72052401746726
Epoch 21 Loss : 2.2793376445770264

29it [00:00, 177.63it/s]
29it [00:00, 188.06it/s]
0it [00:00, ?it/s]

Epoch 22 Accuracy : 89.62882096069869
Epoch 22 Loss : 2.3476452827453613
Epoch 23 Accuracy : 90.82969432314411
Epoch 23 Loss : 2.2532269954681396

29it [00:00, 153.45it/s]
29it [00:00, 178.80it/s]
0it [00:00, ?it/s]

Epoch 24 Accuracy : 90.50218340611353
Epoch 24 Loss : 2.2203266620635986
Epoch 25 Accuracy : 89.62882096069869
Epoch 25 Loss : 2.3295626640319824

29it [00:00, 175.47it/s]
29it [00:00, 177.96it/s]
0it [00:00, ?it/s]

Epoch 26 Accuracy : 90.61135371179039
Epoch 26 Loss : 2.2694287300109863
Epoch 27 Accuracy : 90.06550218340611
Epoch 27 Loss : 2.336580276489258

29it [00:00, 161.68it/s]
29it [00:00, 165.19it/s]
0it [00:00, ?it/s]

Epoch 28 Accuracy : 90.28384279475983
Epoch 28 Loss : 2.273085832595825
Epoch 29 Accuracy : 90.06550218340611
Epoch 29 Loss : 2.4133994579315186

29it [00:00, 172.80it/s]
29it [00:00, 184.91it/s]
0it [00:00, ?it/s]

Epoch 30 Accuracy : 89.8471615720524
Epoch 30 Loss : 2.425769567489624
Epoch 31 Accuracy : 90.17467248908298
Epoch 31 Loss : 2.3188040256500244

29it [00:00, 169.85it/s]
29it [00:00, 181.83it/s]
0it [00:00, ?it/s]

Epoch 32 Accuracy : 90.61135371179039
Epoch 32 Loss : 2.274061441421509
Epoch 33 Accuracy : 90.72052401746726
Epoch 33 Loss : 2.1622562408447266

29it [00:00, 183.82it/s]
29it [00:00, 188.67it/s]
0it [00:00, ?it/s]

Epoch 34 Accuracy : 91.15720524017468
Epoch 34 Loss : 2.104736804962158
Epoch 35 Accuracy : 91.48471615720524
Epoch 35 Loss : 1.9946057796478271

29it [00:00, 167.63it/s]
29it [00:00, 178.92it/s]
0it [00:00, ?it/s]

Epoch 36 Accuracy : 91.70305676855895
Epoch 36 Loss : 1.9427024126052856
Epoch 37 Accuracy : 91.8122270742358
Epoch 37 Loss : 2.002718210220337

29it [00:00, 180.66it/s]
29it [00:00, 181.86it/s]
0it [00:00, ?it/s]

Epoch 38 Accuracy : 91.48471615720524
Epoch 38 Loss : 2.0048084259033203
Epoch 39 Accuracy : 91.48471615720524
Epoch 39 Loss : 1.9937337636947632

29it [00:00, 176.40it/s]
29it [00:00, 177.35it/s]
0it [00:00, ?it/s]

Epoch 40 Accuracy : 91.70305676855895
Epoch 40 Loss : 1.9403319358825684
Epoch 41 Accuracy : 91.70305676855895
Epoch 41 Loss : 1.8877227306365967

29it [00:00, 185.45it/s]
29it [00:00, 188.81it/s]
0it [00:00, ?it/s]

Epoch 42 Accuracy : 92.03056768558952
Epoch 42 Loss : 1.8594614267349243
Epoch 43 Accuracy : 91.70305676855895
Epoch 43 Loss : 1.9383023977279663

29it [00:00, 177.71it/s]
29it [00:00, 186.28it/s]
0it [00:00, ?it/s]

Epoch 44 Accuracy : 91.8122270742358
Epoch 44 Loss : 1.9071202278137207
Epoch 45 Accuracy : 91.5938864628821
Epoch 45 Loss : 1.860056757926941

29it [00:00, 179.54it/s]
29it [00:00, 172.91it/s]
0it [00:00, ?it/s]

Epoch 46 Accuracy : 91.92139737991266
Epoch 46 Loss : 1.8283500671386719
Epoch 47 Accuracy : 91.92139737991266
Epoch 47 Loss : 1.8417915105819702

29it [00:00, 167.46it/s]
29it [00:00, 176.26it/s]
0it [00:00, ?it/s]

Epoch 48 Accuracy : 91.70305676855895
Epoch 48 Loss : 1.8465957641601562
Epoch 49 Accuracy : 91.37554585152839
Epoch 49 Loss : 1.8231245279312134

29it [00:00, 168.70it/s]
29it [00:00, 178.37it/s]
0it [00:00, ?it/s]

Epoch 50 Accuracy : 91.92139737991266
Epoch 50 Loss : 1.802781581878662
Epoch 51 Accuracy : 91.8122270742358
Epoch 51 Loss : 1.8210347890853882

29it [00:00, 179.25it/s]
29it [00:00, 170.53it/s]
0it [00:00, ?it/s]

Epoch 52 Accuracy : 91.5938864628821
Epoch 52 Loss : 1.8287192583084106
Epoch 53 Accuracy : 91.48471615720524
Epoch 53 Loss : 1.8088005781173706

29it [00:00, 177.94it/s]
29it [00:00, 187.66it/s]
0it [00:00, ?it/s]

Epoch 54 Accuracy : 91.26637554585153
Epoch 54 Loss : 1.7994918823242188
Epoch 55 Accuracy : 91.5938864628821
Epoch 55 Loss : 1.7807104587554932

29it [00:00, 178.30it/s]
29it [00:00, 180.75it/s]
0it [00:00, ?it/s]

Epoch 56 Accuracy : 91.8122270742358
Epoch 56 Loss : 1.7890700101852417
Epoch 57 Accuracy : 91.70305676855895
Epoch 57 Loss : 1.778237223625183

29it [00:00, 176.45it/s]
29it [00:00, 176.69it/s]
0it [00:00, ?it/s]

Epoch 58 Accuracy : 91.37554585152839
Epoch 58 Loss : 1.7620995044708252
Epoch 59 Accuracy : 91.8122270742358
Epoch 59 Loss : 1.7536312341690063

29it [00:00, 183.14it/s]
29it [00:00, 164.46it/s]
0it [00:00, ?it/s]

Epoch 60 Accuracy : 91.70305676855895
Epoch 60 Loss : 1.7374088764190674
Epoch 61 Accuracy : 91.37554585152839
Epoch 61 Loss : 1.732466220855713

29it [00:00, 176.24it/s]
29it [00:00, 177.14it/s]
0it [00:00, ?it/s]

Epoch 62 Accuracy : 91.8122270742358
Epoch 62 Loss : 1.731038212776184
Epoch 63 Accuracy : 91.70305676855895
Epoch 63 Loss : 1.7282899618148804

29it [00:00, 171.95it/s]
29it [00:00, 160.00it/s]
0it [00:00, ?it/s]

Epoch 64 Accuracy : 91.37554585152839
Epoch 64 Loss : 1.7295572757720947
Epoch 65 Accuracy : 91.37554585152839
Epoch 65 Loss : 1.7186706066131592

29it [00:00, 184.77it/s]
29it [00:00, 185.84it/s]
0it [00:00, ?it/s]

Epoch 66 Accuracy : 91.5938864628821
Epoch 66 Loss : 1.717613935470581
Epoch 67 Accuracy : 91.5938864628821
Epoch 67 Loss : 1.7117811441421509

29it [00:00, 186.41it/s]
29it [00:00, 190.47it/s]
0it [00:00, ?it/s]

Epoch 68 Accuracy : 91.8122270742358
Epoch 68 Loss : 1.7178587913513184
Epoch 69 Accuracy : 91.5938864628821
Epoch 69 Loss : 1.7028074264526367

29it [00:00, 175.39it/s]
29it [00:00, 178.32it/s]
0it [00:00, ?it/s]

Epoch 70 Accuracy : 91.48471615720524
Epoch 70 Loss : 1.700721025466919
Epoch 71 Accuracy : 91.26637554585153
Epoch 71 Loss : 1.700490117073059

29it [00:00, 173.58it/s]
29it [00:00, 173.82it/s]
0it [00:00, ?it/s]

Epoch 72 Accuracy : 91.5938864628821
Epoch 72 Loss : 1.6960842609405518
Epoch 73 Accuracy : 91.37554585152839
Epoch 73 Loss : 1.6906148195266724

29it [00:00, 174.04it/s]
29it [00:00, 172.23it/s]
0it [00:00, ?it/s]

Epoch 74 Accuracy : 91.70305676855895
Epoch 74 Loss : 1.6952571868896484
Epoch 75 Accuracy : 91.5938864628821
Epoch 75 Loss : 1.684694766998291

29it [00:00, 171.44it/s]
29it [00:00, 173.76it/s]
0it [00:00, ?it/s]

Epoch 76 Accuracy : 91.37554585152839
Epoch 76 Loss : 1.6900330781936646
Epoch 77 Accuracy : 91.5938864628821
Epoch 77 Loss : 1.6869093179702759

29it [00:00, 176.68it/s]
29it [00:00, 177.14it/s]
0it [00:00, ?it/s]

Epoch 78 Accuracy : 91.37554585152839
Epoch 78 Loss : 1.6799752712249756
Epoch 79 Accuracy : 91.5938864628821
Epoch 79 Loss : 1.6772911548614502

29it [00:00, 180.42it/s]
29it [00:00, 184.65it/s]
0it [00:00, ?it/s]

Epoch 80 Accuracy : 91.37554585152839
Epoch 80 Loss : 1.677536964416504
Epoch 81 Accuracy : 91.37554585152839
Epoch 81 Loss : 1.6711077690124512

29it [00:00, 179.17it/s]
29it [00:00, 181.14it/s]
0it [00:00, ?it/s]

Epoch 82 Accuracy : 91.37554585152839
Epoch 82 Loss : 1.6742712259292603
Epoch 83 Accuracy : 91.37554585152839
Epoch 83 Loss : 1.6700166463851929

29it [00:00, 184.82it/s]
29it [00:00, 178.63it/s]
0it [00:00, ?it/s]

Epoch 84 Accuracy : 91.37554585152839
Epoch 84 Loss : 1.6658624410629272
Epoch 85 Accuracy : 91.37554585152839
Epoch 85 Loss : 1.66513991355896

29it [00:00, 182.99it/s]
29it [00:00, 181.93it/s]
0it [00:00, ?it/s]

Epoch 86 Accuracy : 91.37554585152839
Epoch 86 Loss : 1.6654144525527954
Epoch 87 Accuracy : 91.48471615720524
Epoch 87 Loss : 1.662056803703308

29it [00:00, 174.76it/s]
29it [00:00, 168.61it/s]
0it [00:00, ?it/s]

Epoch 88 Accuracy : 91.15720524017468
Epoch 88 Loss : 1.6593114137649536
Epoch 89 Accuracy : 91.48471615720524
Epoch 89 Loss : 1.6609680652618408

29it [00:00, 182.08it/s]
29it [00:00, 186.22it/s]
0it [00:00, ?it/s]

Epoch 90 Accuracy : 91.37554585152839
Epoch 90 Loss : 1.6565017700195312
Epoch 91 Accuracy : 91.48471615720524
Epoch 91 Loss : 1.6599414348602295

29it [00:00, 162.53it/s]
11it [00:00, 105.78it/s]

Epoch 92 Accuracy : 91.48471615720524
Epoch 92 Loss : 1.653198480606079

29it [00:00, 113.00it/s]
29it [00:00, 167.02it/s]
0it [00:00, ?it/s]

Epoch 93 Accuracy : 91.5938864628821
Epoch 93 Loss : 1.6560485363006592
Epoch 94 Accuracy : 91.48471615720524
Epoch 94 Loss : 1.6504207849502563

29it [00:00, 174.39it/s]
14it [00:00, 131.50it/s]

Epoch 95 Accuracy : 91.5938864628821
Epoch 95 Loss : 1.649721384048462

29it [00:00, 142.82it/s]
29it [00:00, 177.16it/s]
0it [00:00, ?it/s]

Epoch 96 Accuracy : 91.37554585152839
Epoch 96 Loss : 1.6489695310592651
Epoch 97 Accuracy : 91.48471615720524
Epoch 97 Loss : 1.650484323501587

29it [00:00, 147.38it/s]
29it [00:00, 179.36it/s]
0it [00:00, ?it/s]

Epoch 98 Accuracy : 91.48471615720524
Epoch 98 Loss : 1.6489826440811157
Epoch 99 Accuracy : 91.8122270742358
Epoch 99 Loss : 1.647173285484314

29it [00:00, 129.48it/s]
29it [00:00, 163.83it/s]
0it [00:00, ?it/s]

Epoch 100 Accuracy : 91.70305676855895
Epoch 100 Loss : 1.649245023727417
Epoch 101 Accuracy : 91.70305676855895
Epoch 101 Loss : 1.6457961797714233

29it [00:00, 179.39it/s]
29it [00:00, 166.16it/s]
0it [00:00, ?it/s]

Epoch 102 Accuracy : 91.8122270742358
Epoch 102 Loss : 1.6440861225128174
Epoch 103 Accuracy : 91.48471615720524
Epoch 103 Loss : 1.643546223640442

29it [00:00, 175.54it/s]
29it [00:00, 185.98it/s]
0it [00:00, ?it/s]

Epoch 104 Accuracy : 91.48471615720524
Epoch 104 Loss : 1.64260995388031
Epoch 105 Accuracy : 91.37554585152839
Epoch 105 Loss : 1.6398556232452393

29it [00:00, 166.26it/s]
29it [00:00, 176.56it/s]
0it [00:00, ?it/s]

Epoch 106 Accuracy : 91.70305676855895
Epoch 106 Loss : 1.6395586729049683
Epoch 107 Accuracy : 91.37554585152839
Epoch 107 Loss : 1.6426599025726318

29it [00:00, 187.40it/s]
29it [00:00, 175.45it/s]
0it [00:00, ?it/s]

Epoch 108 Accuracy : 91.37554585152839
Epoch 108 Loss : 1.6399728059768677
Epoch 109 Accuracy : 91.5938864628821
Epoch 109 Loss : 1.6414982080459595

29it [00:00, 157.41it/s]
29it [00:00, 157.13it/s]
0it [00:00, ?it/s]

Epoch 110 Accuracy : 91.48471615720524
Epoch 110 Loss : 1.637180209159851
Epoch 111 Accuracy : 91.48471615720524
Epoch 111 Loss : 1.6388065814971924

29it [00:00, 171.02it/s]
29it [00:00, 172.97it/s]
0it [00:00, ?it/s]

Epoch 112 Accuracy : 91.8122270742358
Epoch 112 Loss : 1.6383311748504639
Epoch 113 Accuracy : 91.70305676855895
Epoch 113 Loss : 1.6340690851211548

29it [00:00, 145.63it/s]
29it [00:00, 151.53it/s]
0it [00:00, ?it/s]

Epoch 114 Accuracy : 91.48471615720524
Epoch 114 Loss : 1.6342555284500122
Epoch 115 Accuracy : 91.5938864628821
Epoch 115 Loss : 1.6383287906646729

29it [00:00, 166.88it/s]
29it [00:00, 177.21it/s]
0it [00:00, ?it/s]

Epoch 116 Accuracy : 91.48471615720524
Epoch 116 Loss : 1.6346839666366577
Epoch 117 Accuracy : 91.8122270742358
Epoch 117 Loss : 1.6342812776565552

29it [00:00, 176.89it/s]
29it [00:00, 179.04it/s]
0it [00:00, ?it/s]

Epoch 118 Accuracy : 91.70305676855895
Epoch 118 Loss : 1.6330504417419434
Epoch 119 Accuracy : 91.5938864628821
Epoch 119 Loss : 1.630473017692566

29it [00:00, 172.71it/s]
29it [00:00, 155.80it/s]
0it [00:00, ?it/s]

Epoch 120 Accuracy : 91.37554585152839
Epoch 120 Loss : 1.631661057472229
Epoch 121 Accuracy : 91.70305676855895
Epoch 121 Loss : 1.6309515237808228

29it [00:00, 154.07it/s]
29it [00:00, 168.37it/s]
0it [00:00, ?it/s]

Epoch 122 Accuracy : 91.5938864628821
Epoch 122 Loss : 1.62826669216156
Epoch 123 Accuracy : 91.8122270742358
Epoch 123 Loss : 1.6281192302703857

29it [00:00, 165.16it/s]
29it [00:00, 186.58it/s]
0it [00:00, ?it/s]

Epoch 124 Accuracy : 91.5938864628821
Epoch 124 Loss : 1.627437710762024
Epoch 125 Accuracy : 91.48471615720524
Epoch 125 Loss : 1.6266199350357056

29it [00:00, 176.52it/s]
29it [00:00, 180.63it/s]
0it [00:00, ?it/s]

Epoch 126 Accuracy : 91.5938864628821
Epoch 126 Loss : 1.6276544332504272
Epoch 127 Accuracy : 91.5938864628821
Epoch 127 Loss : 1.6281309127807617

29it [00:00, 164.63it/s]
29it [00:00, 185.66it/s]
0it [00:00, ?it/s]

Epoch 128 Accuracy : 91.70305676855895
Epoch 128 Loss : 1.629209280014038
Epoch 129 Accuracy : 91.5938864628821
Epoch 129 Loss : 1.6278319358825684

29it [00:00, 141.53it/s]
12it [00:00, 119.96it/s]

Epoch 130 Accuracy : 91.37554585152839
Epoch 130 Loss : 1.6297657489776611

29it [00:00, 129.45it/s]
13it [00:00, 129.49it/s]

Epoch 131 Accuracy : 91.8122270742358
Epoch 131 Loss : 1.6258848905563354

29it [00:00, 140.69it/s]
29it [00:00, 153.04it/s]
0it [00:00, ?it/s]

Epoch 132 Accuracy : 91.5938864628821
Epoch 132 Loss : 1.624350666999817
Epoch 133 Accuracy : 91.48471615720524
Epoch 133 Loss : 1.6250876188278198

29it [00:00, 174.56it/s]
29it [00:00, 171.77it/s]
0it [00:00, ?it/s]

Epoch 134 Accuracy : 91.70305676855895
Epoch 134 Loss : 1.6256769895553589
Epoch 135 Accuracy : 91.70305676855895
Epoch 135 Loss : 1.6238857507705688

29it [00:00, 174.40it/s]
29it [00:00, 184.58it/s]
0it [00:00, ?it/s]

Epoch 136 Accuracy : 91.70305676855895
Epoch 136 Loss : 1.623263955116272
Epoch 137 Accuracy : 91.5938864628821
Epoch 137 Loss : 1.6260147094726562

29it [00:00, 164.42it/s]
29it [00:00, 175.94it/s]
0it [00:00, ?it/s]

Epoch 138 Accuracy : 91.5938864628821
Epoch 138 Loss : 1.6233266592025757
Epoch 139 Accuracy : 91.70305676855895
Epoch 139 Loss : 1.6253706216812134

29it [00:00, 173.48it/s]
29it [00:00, 168.16it/s]
0it [00:00, ?it/s]

Epoch 140 Accuracy : 91.70305676855895
Epoch 140 Loss : 1.6228115558624268
Epoch 141 Accuracy : 91.5938864628821
Epoch 141 Loss : 1.6234650611877441

29it [00:00, 180.82it/s]
29it [00:00, 189.45it/s]
0it [00:00, ?it/s]

Epoch 142 Accuracy : 91.48471615720524
Epoch 142 Loss : 1.622348666191101
Epoch 143 Accuracy : 91.5938864628821
Epoch 143 Loss : 1.6226030588150024

29it [00:00, 183.28it/s]
15it [00:00, 146.76it/s]

Epoch 144 Accuracy : 91.48471615720524
Epoch 144 Loss : 1.6253985166549683

29it [00:00, 141.94it/s]
15it [00:00, 144.57it/s]

Epoch 145 Accuracy : 91.8122270742358
Epoch 145 Loss : 1.6237809658050537

29it [00:00, 100.23it/s]
29it [00:00, 159.59it/s]
0it [00:00, ?it/s]

Epoch 146 Accuracy : 91.5938864628821
Epoch 146 Loss : 1.6268179416656494
Epoch 147 Accuracy : 91.70305676855895
Epoch 147 Loss : 1.6257232427597046

29it [00:00, 132.79it/s]
29it [00:00, 164.07it/s]
0it [00:00, ?it/s]

Epoch 148 Accuracy : 91.8122270742358
Epoch 148 Loss : 1.6227636337280273
Epoch 149 Accuracy : 91.92139737991266
Epoch 149 Loss : 1.622753620147705

29it [00:00, 172.22it/s]
29it [00:00, 163.91it/s]
0it [00:00, ?it/s]

Epoch 150 Accuracy : 91.8122270742358
Epoch 150 Loss : 1.6198228597640991
Epoch 151 Accuracy : 91.48471615720524
Epoch 151 Loss : 1.6190992593765259

29it [00:00, 149.94it/s]
29it [00:00, 178.31it/s]
0it [00:00, ?it/s]

Epoch 152 Accuracy : 91.5938864628821
Epoch 152 Loss : 1.6201003789901733
Epoch 153 Accuracy : 91.70305676855895
Epoch 153 Loss : 1.6205947399139404

29it [00:00, 175.31it/s]
29it [00:00, 188.48it/s]
0it [00:00, ?it/s]

Epoch 154 Accuracy : 91.8122270742358
Epoch 154 Loss : 1.621485710144043
Epoch 155 Accuracy : 91.5938864628821
Epoch 155 Loss : 1.6195640563964844

29it [00:00, 169.00it/s]
29it [00:00, 165.32it/s]
0it [00:00, ?it/s]

Epoch 156 Accuracy : 91.70305676855895
Epoch 156 Loss : 1.6207958459854126
Epoch 157 Accuracy : 91.70305676855895
Epoch 157 Loss : 1.6196075677871704

29it [00:00, 183.72it/s]
29it [00:00, 166.77it/s]
0it [00:00, ?it/s]

Epoch 158 Accuracy : 91.92139737991266
Epoch 158 Loss : 1.617577075958252
Epoch 159 Accuracy : 91.8122270742358
Epoch 159 Loss : 1.6206172704696655

29it [00:00, 143.00it/s]
29it [00:00, 153.41it/s]
0it [00:00, ?it/s]

Epoch 160 Accuracy : 91.70305676855895
Epoch 160 Loss : 1.6161296367645264
Epoch 161 Accuracy : 92.03056768558952
Epoch 161 Loss : 1.6184252500534058

29it [00:00, 145.46it/s]
29it [00:00, 189.59it/s]
0it [00:00, ?it/s]

Epoch 162 Accuracy : 92.03056768558952
Epoch 162 Loss : 1.6175748109817505
Epoch 163 Accuracy : 91.8122270742358
Epoch 163 Loss : 1.6187317371368408

29it [00:00, 183.00it/s]
13it [00:00, 128.23it/s]

Epoch 164 Accuracy : 91.8122270742358
Epoch 164 Loss : 1.6296756267547607

29it [00:00, 135.40it/s]
29it [00:00, 168.81it/s]
0it [00:00, ?it/s]

Epoch 165 Accuracy : 92.13973799126637
Epoch 165 Loss : 1.6413379907608032
Epoch 166 Accuracy : 92.03056768558952
Epoch 166 Loss : 1.6375805139541626

29it [00:00, 172.55it/s]
29it [00:00, 151.37it/s]
0it [00:00, ?it/s]

Epoch 167 Accuracy : 92.03056768558952
Epoch 167 Loss : 1.6343404054641724
Epoch 168 Accuracy : 92.03056768558952
Epoch 168 Loss : 1.6233322620391846

29it [00:00, 158.37it/s]
29it [00:00, 174.40it/s]
0it [00:00, ?it/s]

Epoch 169 Accuracy : 92.03056768558952
Epoch 169 Loss : 1.6257712841033936
Epoch 170 Accuracy : 92.03056768558952
Epoch 170 Loss : 1.6185778379440308

29it [00:00, 167.11it/s]
29it [00:00, 161.01it/s]
0it [00:00, ?it/s]

Epoch 171 Accuracy : 91.92139737991266
Epoch 171 Loss : 1.6193350553512573
Epoch 172 Accuracy : 92.03056768558952
Epoch 172 Loss : 1.616104006767273

29it [00:00, 171.37it/s]
29it [00:00, 171.50it/s]
0it [00:00, ?it/s]

Epoch 173 Accuracy : 92.13973799126637
Epoch 173 Loss : 1.617698311805725
Epoch 174 Accuracy : 92.24890829694323
Epoch 174 Loss : 1.6145402193069458

29it [00:00, 149.04it/s]
29it [00:00, 169.10it/s]
0it [00:00, ?it/s]

Epoch 175 Accuracy : 91.8122270742358
Epoch 175 Loss : 1.6156810522079468
Epoch 176 Accuracy : 92.13973799126637
Epoch 176 Loss : 1.6156929731369019

29it [00:00, 175.82it/s]
29it [00:00, 175.14it/s]
0it [00:00, ?it/s]

Epoch 177 Accuracy : 91.70305676855895
Epoch 177 Loss : 1.6134843826293945
Epoch 178 Accuracy : 92.03056768558952
Epoch 178 Loss : 1.6139637231826782

29it [00:00, 174.23it/s]
29it [00:00, 183.15it/s]
0it [00:00, ?it/s]

Epoch 179 Accuracy : 92.03056768558952
Epoch 179 Loss : 1.6128802299499512
Epoch 180 Accuracy : 91.92139737991266
Epoch 180 Loss : 1.6132683753967285

29it [00:00, 141.93it/s]
29it [00:00, 155.17it/s]
0it [00:00, ?it/s]

Epoch 181 Accuracy : 91.92139737991266
Epoch 181 Loss : 1.6303454637527466
Epoch 182 Accuracy : 92.13973799126637
Epoch 182 Loss : 1.6178330183029175

29it [00:00, 162.70it/s]
29it [00:00, 181.06it/s]
0it [00:00, ?it/s]

Epoch 183 Accuracy : 91.8122270742358
Epoch 183 Loss : 1.6190667152404785
Epoch 184 Accuracy : 92.03056768558952
Epoch 184 Loss : 1.614828109741211

29it [00:00, 184.30it/s]
29it [00:00, 181.31it/s]
0it [00:00, ?it/s]

Epoch 185 Accuracy : 92.13973799126637
Epoch 185 Loss : 1.6139723062515259
Epoch 186 Accuracy : 92.03056768558952
Epoch 186 Loss : 1.613112211227417

29it [00:00, 169.61it/s]
29it [00:00, 170.57it/s]
0it [00:00, ?it/s]

Epoch 187 Accuracy : 91.92139737991266
Epoch 187 Loss : 1.6125212907791138
Epoch 188 Accuracy : 91.92139737991266
Epoch 188 Loss : 1.6127060651779175

29it [00:00, 196.37it/s]
29it [00:00, 188.64it/s]
0it [00:00, ?it/s]

Epoch 189 Accuracy : 91.92139737991266
Epoch 189 Loss : 1.612476110458374
Epoch 190 Accuracy : 92.03056768558952
Epoch 190 Loss : 1.6140574216842651

29it [00:00, 138.69it/s]
11it [00:00, 106.06it/s]

Epoch 191 Accuracy : 91.92139737991266
Epoch 191 Loss : 1.6134421825408936

29it [00:00, 123.56it/s]
29it [00:00, 173.23it/s]
0it [00:00, ?it/s]

Epoch 192 Accuracy : 92.13973799126637
Epoch 192 Loss : 1.6140447854995728
Epoch 193 Accuracy : 92.13973799126637
Epoch 193 Loss : 1.610988974571228

29it [00:00, 175.91it/s]
29it [00:00, 197.20it/s]
0it [00:00, ?it/s]

Epoch 194 Accuracy : 92.03056768558952
Epoch 194 Loss : 1.6126359701156616
Epoch 195 Accuracy : 92.13973799126637
Epoch 195 Loss : 1.6119194030761719

29it [00:00, 198.45it/s]
29it [00:00, 189.03it/s]
0it [00:00, ?it/s]

Epoch 196 Accuracy : 92.03056768558952
Epoch 196 Loss : 1.6121553182601929
Epoch 197 Accuracy : 91.8122270742358
Epoch 197 Loss : 1.6142054796218872

29it [00:00, 173.27it/s]
12it [00:00, 112.98it/s]

Epoch 198 Accuracy : 91.92139737991266
Epoch 198 Loss : 1.6110283136367798

29it [00:00, 116.07it/s]
15it [00:00, 148.56it/s]

Epoch 199 Accuracy : 92.03056768558952
Epoch 199 Loss : 1.613629698753357

29it [00:00, 138.89it/s]

Epoch 200 Accuracy : 92.03056768558952
Epoch 200 Loss : 1.6124478578567505

### Testing

In [220]:
def test(model,x):
    output=model(x.float())
    return output

In [221]:
data_test=Gen_Dataset('cleaned_test.csv')

In [222]:
data_test=DataLoader(dataset=data_test,batch_size=32,shuffle=False)

In [224]:
for bidx, batch in tqdm(enumerate(data_test)):
        x_test, y_test = batch['inp'], batch['oup']
        predictions = test(netw,x_test)
        for idx, i in enumerate(predictions):
            i  = torch.round(i)
            if i == y_test[idx]:
                correct += 1
        acc = (correct/len(data_test))

13it [00:00, 380.90it/s]

In [225]:
print(acc)

90.15384615384616